# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e04ffa2d4b764c0440cd6c145c338bb10d117dbe166b1ec69532aa589c632778b5477a88f5781e533da6683cdbea377b764e35f203b775a63e37bf97fc15055

test:
  secret_key_base: 8499ab99d7b66f654f813de3c009c7261658f68097677d5590baa3dcad0786a37f10943c6a43788ac4bfaa81ea2a9e98e3f79ce790512fbc2621af929a828497

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
